networks:
  sonic:  # For Sonic L1
    rpc_url: "https://rpc.soniclabs.com"
    chain_id: 146
  arbitrum:  # For Arbitrum operations
    rpc_url: "https://arbitrum-mainnet.infura.io/v3/${ARB_RPC_KEY}"
    chain_id: 42161

contracts:
  sonic:
    sonic_vault: "0xa3c0eCA00D2B76b4d1F170b0AB3FdeA16C180186"
    sonic_oracle: "0xE68e0C66950a7e02335fc9f44daa05D115c4E88B"
    sonic_zapper: "0xe25A2B256ffb3AD73678d5e80DE8d2F6022fAb21"
  arbitrum:
    debridge_gate: "0x43dE2d77BF8027e25dBD179B491e8d64f38398aA"

strategy:
  reinvest_threshold: 0.05  # Example: Only reinvest if rewards > 5%
  rebalance_interval: 86400  # Rebalance every 24h (in seconds)
